[03-15 11:57:55]: [INFO] Created column 'regdate' and set the current timestamp, 1710503875871, to all 0 rows
[03-15 11:57:55]: [INFO] SQLite Setup finished
[03-15 11:57:55]: [INFO] No supported permissions system found! Permissions are disabled!
[03-15 11:57:56]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[03-15 11:57:56]: [INFO] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[03-15 11:57:56]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[03-15 11:57:56]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[03-15 11:57:56]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[03-15 11:57:56]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[03-15 11:57:56]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[03-15 11:58:04]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:22:44]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:22:46]: [WARN] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 15 milliseconds ago.  The last packet sent successfully to the server was 14 milliseconds ago.
[03-15 14:22:46]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 15 milliseconds ago.  The last packet sent successfully to the server was 14 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:22:46]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:22:46]: [WARN] Could not create data source: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 15 milliseconds ago.  The last packet sent successfully to the server was 14 milliseconds ago.
[03-15 14:22:46]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 15 milliseconds ago.  The last packet sent successfully to the server was 14 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:22:46]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:22:46]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 15 milliseconds ago.  The last packet sent successfully to the server was 14 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:22:46]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:25:13]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:25:14]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:25:14]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:25:14]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:25:14]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:25:14]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:25:14]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:25:14]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more

[03-15 14:25:14]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:27:17]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:27:19]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:27:19]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:27:19]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:27:19]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:27:19]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:27:19]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:27:19]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more

[03-15 14:27:19]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:30:32]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:30:33]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:30:33]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:30:33]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:30:33]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:30:33]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:30:33]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:30:33]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more

[03-15 14:30:33]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:31:07]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:31:08]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:31:08]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:31:08]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:31:08]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:31:08]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:31:08]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:31:08]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more

[03-15 14:31:08]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:35:51]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:35:52]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:35:52]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:35:52]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:35:52]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[03-15 14:35:52]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)

[03-15 14:35:52]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:35:52]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more

[03-15 14:35:52]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:37:41]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:37:42]: [WARN] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 111 milliseconds ago.  The last packet sent successfully to the server was 110 milliseconds ago.
[03-15 14:37:42]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 111 milliseconds ago.  The last packet sent successfully to the server was 110 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:37:42]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:37:42]: [WARN] Could not create data source: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 111 milliseconds ago.  The last packet sent successfully to the server was 110 milliseconds ago.
[03-15 14:37:42]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 111 milliseconds ago.  The last packet sent successfully to the server was 110 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:37:42]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:37:42]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 111 milliseconds ago.  The last packet sent successfully to the server was 110 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 46 more

[03-15 14:37:42]: [INFO] AuthMe 5.6.0-beta2-b2453 disabled!
[03-15 14:41:57]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:41:58]: [WARN] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 98 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
[03-15 14:41:58]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 98 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 47 more

[03-15 14:41:58]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:41:58]: [WARN] Could not create data source: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 98 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
[03-15 14:41:58]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 98 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 47 more

[03-15 14:41:58]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:41:58]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 98 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:247)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
	... 47 more

[03-15 14:41:58]: [INFO] AuthMe 5.4.0-b1877 disabled!
[03-15 14:44:16]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:44:17]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
[03-15 14:44:17]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:44:17]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:44:17]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
[03-15 14:44:17]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:44:17]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:44:17]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more
Caused by: java.lang.NumberFormatException: For input string: "eaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:44:17]: [INFO] AuthMe 5.4.0-b1877 disabled!
[03-15 14:45:35]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-15 14:45:36]: [WARN] Can't initialize the MySQL database: [MySQLNonTransientConnectionException]: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
[03-15 14:45:36]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:45:36]: [WARN] Please check your database settings in the config.yml file!
[03-15 14:45:36]: [WARN] Could not create data source: [MySQLNonTransientConnectionException]: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
[03-15 14:45:36]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:45:36]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[03-15 14:45:36]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:314)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 19 more
Caused by: java.lang.NumberFormatException: For input string: "myeaglr-felixplays25-6ed8.a.aivencloud.com:11592"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.mysql.jdbc.NonRegisteringDriver.port(NonRegisteringDriver.java:831)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	... 32 more

[03-15 14:45:36]: [INFO] AuthMe 5.4.0-b1877 disabled!
